# STRING AND NUMERIC VALUE CAN OPERATE TOGETHER WITH "*"....
a , b = 2 , 3
text = "@"
print(a*text*b) # THIS WILL PRINT "@" (a*b)TIMES...

# STRING AND STRING CAN OPERATE WITH "+"....
a , b = "2" , 3
text = "@"
print((a+text)*b) # THIS WILL PRINT THE SUM OF TWO STRINGS i.e. a AND text (b) TIMES...