# BLOCK OF STATEMENTS THAT PERFORMS SPECIFIC TASKS....

def calc_sum(a,b):   # CALLING AND GIVING A NAME TO OUR FUNCTION THAT WILL PERFORM THE GIVEN SPECIFIC TASK...
    sum = a + b
    print(sum)
    return sum

calc_sum(3,5) # ACD TO DEFINITION OF FUNCTION THIS WILL GIVE THE SUM TO 3 AND 5
calc_sum(7,9) # ACD TO DEFINITION OF FUNCTION THIS WILL GIVE THE SUM TO 7 AND 9