# LIST IS A BUILT IN DATA TYPE THAT STORES VALUE OF DIFFERENT TYPE....

list = [2 , 1 , 3]
print(list)

#  TUPPLES IS A BUILT IN DATATYPE THAT LETS US CREATE IMMUTABLE SEQUENCE OF VALUES....

tup = (2 , 1 , 3)
print(tup)