# AN OPERATOR IS A SYMBOL THAT PERFORMS A CERTAIN OPERATIONS BETWEEN OPERANDS....
# ARITHMATIC OPERATORS:-
a = 5
b = 6
c = a + b
d = a - b
e = a * b
f = a / b
g = a % b
h = a ** b

print(c) # THIS WILL PRINT THE SUM OF a AND b
print(d) # THIS WILL PRINT THE DIFFERENCE OF a AND b
print(e) # THIS WILL PRINT THE MULTIPLICATION OF a AND b
print(f) # THIS WILL PRINT THE DEVISION OF a AND b
print(g) # THIS WILL PRINT THE REMAINDER WHEN a IS DEVIDED BY b
print(h) # THIS WILL PRINT THE VALUE OF a TO THE POWER b